CREATE TABLE IF NOT EXISTS shop
(
    shop_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name VARCHAR(100) NOT NULL,
    shop_address VARCHAR(200) NOT NULL,
    shop_phone VARCHAR(12) NOT NULL,
    shop_workhours VARCHAR(12) NOT NULL,
    shop_picture VARCHAR(300)
);