CREATE TABLE IF NOT EXISTS product
(
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    product_price DECIMAL(6, 2) NOT NULL,
    product_old_price DECIMAL(6, 2) NOT NULL,
    basket_quantity INT NOT NULL,
    product_description VARCHAR(300) NOT NULL,
    product_amount INT NOT NULL,
    picture_path VARCHAR(100) NOT NULL,
    category_id BIGINT REFERENCES category(category_id) ON DELETE CASCADE NOT NULL
);

