CREATE TABLE IF NOT EXISTS points
(
    points_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    points_name VARCHAR(100) NOT NULL,
    points_address VARCHAR(200) NOT NULL,
    points_phone VARCHAR(12) NOT NULL,
    points_workhours VARCHAR(12) NOT NULL,
    points_picture VARCHAR(300)
    );