CREATE TABLE IF NOT EXISTS my_order
(
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_total DECIMAL(6, 2) NOT NULL,
    order_status BOOLEAN NOT NULL,
    user_id BIGINT REFERENCES my_user(user_id) ON DELETE CASCADE NOT NULL,
    delivery_id BIGINT REFERENCES delivery(delivery_id) ON DELETE CASCADE,
    payment_id BIGINT REFERENCES payment(payment_id) ON DELETE CASCADE,
    shop_id BIGINT REFERENCES shop(shop_id) ON DELETE CASCADE NOT NULL
);