name: the_store_app
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  core:
    path: ../core
  elementary: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  decimal: ^2.3.2
  retrofit: ^4.0.1
  dio: ^5.1.1
  auto_route: ^7.1.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3
  auto_route_generator: ^7.0.0

flutter:
  uses-material-design: true
