name: the_store_app
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  core:
    path: ../core
  elementary: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  decimal: ^2.3.2
  retrofit: ^4.0.1
  dio: ^5.1.1
  auto_route: ^7.1.0
  provider: ^6.0.5
  google_fonts: ^4.0.4
  pretty_dio_logger: ^1.3.1
  logger: ^1.3.0
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_crashlytics: ^3.3.1
  firebase_remote_config: ^4.2.2
  firebase_performance: ^0.9.2+1
  firebase_auth: ^4.6.2
  smooth_page_indicator: ^1.1.0
  yandex_mapkit: ^3.2.0
  shared_preferences: ^2.1.1
  kiwi: ^4.1.0
  cached_network_image: ^3.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  webview_flutter: ^4.2.2
  pinput: ^2.2.31
  flutter_markdown: ^0.6.15
  url_launcher: ^6.1.11
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  flutter_masked_text2: ^0.9.1
  dadata_suggestions:
    git:
      url: https://github.com/AurelVU/dadata_suggestions.git
      ref: null_saffety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+3
  auto_route_generator: ^7.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
